// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/inventory/product.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductIDRequest) Reset() {
	*x = ProductIDRequest{}
	mi := &file_proto_inventory_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIDRequest) ProtoMessage() {}

func (x *ProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIDRequest.ProtoReflect.Descriptor instead.
func (*ProductIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	FrameSize     string                 `protobuf:"bytes,6,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	WheelSize     string                 `protobuf:"bytes,7,opt,name=wheel_size,json=wheelSize,proto3" json:"wheel_size,omitempty"`
	Color         string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Weight        float64                `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	BikeType      string                 `protobuf:"bytes,10,opt,name=bike_type,json=bikeType,proto3" json:"bike_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_inventory_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetFrameSize() string {
	if x != nil {
		return x.FrameSize
	}
	return ""
}

func (x *CreateProductRequest) GetWheelSize() string {
	if x != nil {
		return x.WheelSize
	}
	return ""
}

func (x *CreateProductRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetBikeType() string {
	if x != nil {
		return x.BikeType
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	FrameSize     string                 `protobuf:"bytes,7,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	WheelSize     string                 `protobuf:"bytes,8,opt,name=wheel_size,json=wheelSize,proto3" json:"wheel_size,omitempty"`
	Color         string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	Weight        float64                `protobuf:"fixed64,10,opt,name=weight,proto3" json:"weight,omitempty"`
	BikeType      string                 `protobuf:"bytes,11,opt,name=bike_type,json=bikeType,proto3" json:"bike_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_inventory_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateProductRequest) GetFrameSize() string {
	if x != nil {
		return x.FrameSize
	}
	return ""
}

func (x *UpdateProductRequest) GetWheelSize() string {
	if x != nil {
		return x.WheelSize
	}
	return ""
}

func (x *UpdateProductRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetBikeType() string {
	if x != nil {
		return x.BikeType
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	FrameSize     string                 `protobuf:"bytes,7,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	WheelSize     string                 `protobuf:"bytes,8,opt,name=wheel_size,json=wheelSize,proto3" json:"wheel_size,omitempty"`
	Color         string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	Weight        float64                `protobuf:"fixed64,10,opt,name=weight,proto3" json:"weight,omitempty"`
	BikeType      string                 `protobuf:"bytes,11,opt,name=bike_type,json=bikeType,proto3" json:"bike_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_inventory_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductResponse) GetFrameSize() string {
	if x != nil {
		return x.FrameSize
	}
	return ""
}

func (x *ProductResponse) GetWheelSize() string {
	if x != nil {
		return x.WheelSize
	}
	return ""
}

func (x *ProductResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ProductResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductResponse) GetBikeType() string {
	if x != nil {
		return x.BikeType
	}
	return ""
}

func (x *ProductResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	InStock       bool                   `protobuf:"varint,4,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	BikeType      string                 `protobuf:"bytes,5,opt,name=bike_type,json=bikeType,proto3" json:"bike_type,omitempty"`
	FrameSize     string                 `protobuf:"bytes,6,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	WheelSize     string                 `protobuf:"bytes,7,opt,name=wheel_size,json=wheelSize,proto3" json:"wheel_size,omitempty"`
	Color         string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	MaxWeight     float64                `protobuf:"fixed64,9,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Page          int32                  `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,11,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilter) Reset() {
	*x = ProductFilter{}
	mi := &file_proto_inventory_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilter) ProtoMessage() {}

func (x *ProductFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilter.ProtoReflect.Descriptor instead.
func (*ProductFilter) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductFilter) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductFilter) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProductFilter) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProductFilter) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ProductFilter) GetBikeType() string {
	if x != nil {
		return x.BikeType
	}
	return ""
}

func (x *ProductFilter) GetFrameSize() string {
	if x != nil {
		return x.FrameSize
	}
	return ""
}

func (x *ProductFilter) GetWheelSize() string {
	if x != nil {
		return x.WheelSize
	}
	return ""
}

func (x *ProductFilter) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ProductFilter) GetMaxWeight() float64 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

func (x *ProductFilter) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductFilter) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_inventory_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ProductFilter         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_inventory_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsRequest) GetFilter() *ProductFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_proto_inventory_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProductQuantity     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_proto_inventory_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{8}
}

func (x *CheckStockRequest) GetItems() []*ProductQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProductQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductQuantity) Reset() {
	*x = ProductQuantity{}
	mi := &file_proto_inventory_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductQuantity) ProtoMessage() {}

func (x *ProductQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductQuantity.ProtoReflect.Descriptor instead.
func (*ProductQuantity) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{9}
}

func (x *ProductQuantity) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductQuantity) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckStockResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Available        bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	UnavailableItems []*ProductQuantity     `protobuf:"bytes,2,rep,name=unavailable_items,json=unavailableItems,proto3" json:"unavailable_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_proto_inventory_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_product_proto_rawDescGZIP(), []int{10}
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockResponse) GetUnavailableItems() []*ProductQuantity {
	if x != nil {
		return x.UnavailableItems
	}
	return nil
}

var File_proto_inventory_product_proto protoreflect.FileDescriptor

const file_proto_inventory_product_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/inventory/product.proto\x12\tinventory\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x10ProductIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"frame_size\x18\x06 \x01(\tR\tframeSize\x12\x1d\n" +
	"\n" +
	"wheel_size\x18\a \x01(\tR\twheelSize\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\t \x01(\x01R\x06weight\x12\x1b\n" +
	"\tbike_type\x18\n" +
	" \x01(\tR\bbikeType\"\xb2\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"frame_size\x18\a \x01(\tR\tframeSize\x12\x1d\n" +
	"\n" +
	"wheel_size\x18\b \x01(\tR\twheelSize\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x01R\x06weight\x12\x1b\n" +
	"\tbike_type\x18\v \x01(\tR\bbikeType\"\xa3\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"frame_size\x18\a \x01(\tR\tframeSize\x12\x1d\n" +
	"\n" +
	"wheel_size\x18\b \x01(\tR\twheelSize\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\x01R\x06weight\x12\x1b\n" +
	"\tbike_type\x18\v \x01(\tR\bbikeType\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc6\x02\n" +
	"\rProductFilter\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tmin_price\x18\x02 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\x12\x19\n" +
	"\bin_stock\x18\x04 \x01(\bR\ainStock\x12\x1b\n" +
	"\tbike_type\x18\x05 \x01(\tR\bbikeType\x12\x1d\n" +
	"\n" +
	"frame_size\x18\x06 \x01(\tR\tframeSize\x12\x1d\n" +
	"\n" +
	"wheel_size\x18\a \x01(\tR\twheelSize\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"max_weight\x18\t \x01(\x01R\tmaxWeight\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\v \x01(\x05R\bpageSize\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13ListProductsRequest\x120\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.inventory.ProductFilterR\x06filter\"\x95\x01\n" +
	"\x14ListProductsResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.inventory.ProductResponseR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"E\n" +
	"\x11CheckStockRequest\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.inventory.ProductQuantityR\x05items\"L\n" +
	"\x0fProductQuantity\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"{\n" +
	"\x12CheckStockResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12G\n" +
	"\x11unavailable_items\x18\x02 \x03(\v2\x1a.inventory.ProductQuantityR\x10unavailableItems2\xd8\x03\n" +
	"\x0eProductService\x12L\n" +
	"\rCreateProduct\x12\x1f.inventory.CreateProductRequest\x1a\x1a.inventory.ProductResponse\x12E\n" +
	"\n" +
	"GetProduct\x12\x1b.inventory.ProductIDRequest\x1a\x1a.inventory.ProductResponse\x12L\n" +
	"\rUpdateProduct\x12\x1f.inventory.UpdateProductRequest\x1a\x1a.inventory.ProductResponse\x12G\n" +
	"\rDeleteProduct\x12\x1b.inventory.ProductIDRequest\x1a\x19.inventory.DeleteResponse\x12O\n" +
	"\fListProducts\x12\x1e.inventory.ListProductsRequest\x1a\x1f.inventory.ListProductsResponse\x12I\n" +
	"\n" +
	"CheckStock\x12\x1c.inventory.CheckStockRequest\x1a\x1d.inventory.CheckStockResponseB\x11Z\x0fproto/inventoryb\x06proto3"

var (
	file_proto_inventory_product_proto_rawDescOnce sync.Once
	file_proto_inventory_product_proto_rawDescData []byte
)

func file_proto_inventory_product_proto_rawDescGZIP() []byte {
	file_proto_inventory_product_proto_rawDescOnce.Do(func() {
		file_proto_inventory_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_product_proto_rawDesc), len(file_proto_inventory_product_proto_rawDesc)))
	})
	return file_proto_inventory_product_proto_rawDescData
}

var file_proto_inventory_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_inventory_product_proto_goTypes = []any{
	(*ProductIDRequest)(nil),      // 0: inventory.ProductIDRequest
	(*CreateProductRequest)(nil),  // 1: inventory.CreateProductRequest
	(*UpdateProductRequest)(nil),  // 2: inventory.UpdateProductRequest
	(*ProductResponse)(nil),       // 3: inventory.ProductResponse
	(*ProductFilter)(nil),         // 4: inventory.ProductFilter
	(*DeleteResponse)(nil),        // 5: inventory.DeleteResponse
	(*ListProductsRequest)(nil),   // 6: inventory.ListProductsRequest
	(*ListProductsResponse)(nil),  // 7: inventory.ListProductsResponse
	(*CheckStockRequest)(nil),     // 8: inventory.CheckStockRequest
	(*ProductQuantity)(nil),       // 9: inventory.ProductQuantity
	(*CheckStockResponse)(nil),    // 10: inventory.CheckStockResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_inventory_product_proto_depIdxs = []int32{
	11, // 0: inventory.ProductResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: inventory.ProductResponse.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: inventory.ListProductsRequest.filter:type_name -> inventory.ProductFilter
	3,  // 3: inventory.ListProductsResponse.products:type_name -> inventory.ProductResponse
	9,  // 4: inventory.CheckStockRequest.items:type_name -> inventory.ProductQuantity
	9,  // 5: inventory.CheckStockResponse.unavailable_items:type_name -> inventory.ProductQuantity
	1,  // 6: inventory.ProductService.CreateProduct:input_type -> inventory.CreateProductRequest
	0,  // 7: inventory.ProductService.GetProduct:input_type -> inventory.ProductIDRequest
	2,  // 8: inventory.ProductService.UpdateProduct:input_type -> inventory.UpdateProductRequest
	0,  // 9: inventory.ProductService.DeleteProduct:input_type -> inventory.ProductIDRequest
	6,  // 10: inventory.ProductService.ListProducts:input_type -> inventory.ListProductsRequest
	8,  // 11: inventory.ProductService.CheckStock:input_type -> inventory.CheckStockRequest
	3,  // 12: inventory.ProductService.CreateProduct:output_type -> inventory.ProductResponse
	3,  // 13: inventory.ProductService.GetProduct:output_type -> inventory.ProductResponse
	3,  // 14: inventory.ProductService.UpdateProduct:output_type -> inventory.ProductResponse
	5,  // 15: inventory.ProductService.DeleteProduct:output_type -> inventory.DeleteResponse
	7,  // 16: inventory.ProductService.ListProducts:output_type -> inventory.ListProductsResponse
	10, // 17: inventory.ProductService.CheckStock:output_type -> inventory.CheckStockResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_inventory_product_proto_init() }
func file_proto_inventory_product_proto_init() {
	if File_proto_inventory_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_product_proto_rawDesc), len(file_proto_inventory_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_product_proto_goTypes,
		DependencyIndexes: file_proto_inventory_product_proto_depIdxs,
		MessageInfos:      file_proto_inventory_product_proto_msgTypes,
	}.Build()
	File_proto_inventory_product_proto = out.File
	file_proto_inventory_product_proto_goTypes = nil
	file_proto_inventory_product_proto_depIdxs = nil
}
